// This file will be auto-generated by Supabase CLI (supabase gen types typescript)
// For now, provide a placeholder that matches the expected shape.
// Run `npx supabase gen types typescript --local > src/database.types.ts` after DB setup.

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
