// This file will be auto-generated by Supabase CLI once the database is set up.
// Run: npx supabase gen types typescript --local > src/database.types.ts
// Manual definitions below keep type safety until then.

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          email: string | null;
          avatar_url: string | null;
          locale: string;
          timezone: string;
          is_guest: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          name: string;
          email?: string | null;
          avatar_url?: string | null;
          locale?: string;
          timezone?: string;
          is_guest?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string | null;
          avatar_url?: string | null;
          locale?: string;
          timezone?: string;
          is_guest?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
